import http from "node:http";

export interface GeoResponse {
	lat?: number;
	lon?: number;
	error?: string;
}

export class Geo {
	public static async getGeolocation(address: string): Promise<GeoResponse> {
		const encodedAddress = encodeURIComponent(address);
		const apiURL = `http://cs310.students.cs.ubc.ca:11316/api/v1/project_team154/${encodedAddress}`;
		// Generated by ChatGPT VIBECODE SLOP
		return new Promise((resolve) => {
			http.get(apiURL, (res) => {
				let data = "";
				res.on("data", (chunk) => {
					data += chunk;
				});
				res.on("end", () => {
					try {
						resolve(JSON.parse(data));
					} catch (err: any) {
						resolve({error: err.message ?? "JSON parse error"});
					}
				})
			}).on("error", (err: any) => {
				resolve({error: err.message});
			});
		});
	}
}
